version: 2.1
jobs:
  check_sa:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "test"

workflows:
  build:
    jobs:
      - check_sa:
          context: 
            - org-default-build
